# Generated by Django 3.2.15 on 2024-04-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketAdmin', '0002_grocrey_gamm_vegitables_vamm_alter_grocrey_gimg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vegitablee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnamee', models.CharField(max_length=30)),
                ('vpricee', models.IntegerField()),
                ('vinfoe', models.TextField()),
                ('vamme', models.CharField(max_length=30, null=True)),
                ('vimge', models.ImageField(upload_to='static/imagesv/')),
            ],
        ),
    ]
