# Generated by Django 3.2.15 on 2024-04-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketAdmin', '0003_vegitablee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField(blank=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketAdmin.platform')),
            ],
        ),
        migrations.DeleteModel(
            name='vegitablee',
        ),
        migrations.RemoveField(
            model_name='vegitables',
            name='vprice',
        ),
        migrations.AddField(
            model_name='productplatform',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketAdmin.vegitables'),
        ),
    ]
