# Generated by Django 3.2.15 on 2024-04-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketAdmin', '0004_auto_20240427_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productplatform',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='productplatform',
            name='product',
        ),
        migrations.AddField(
            model_name='vegitables',
            name='vprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grocrey',
            name='gprice',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='ProductPlatform',
        ),
    ]
