# Generated by Django 3.2.15 on 2024-04-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketAdmin', '0005_auto_20240427_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
